# Generated by Django 4.2.29 on 2026-03-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('recliner', 'Recliner')], default='regular', max_length=10)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('screen', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ShowtimeSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('locked', 'Locked'), ('booked', 'Booked')], default='available', max_length=10)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime_seats', to='seats.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime_seats', to='movies.showtime')),
            ],
            options={
                'ordering': ['seat__row', 'seat__number'],
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
